routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\UsuariosController;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
/* Route::get('/home', 'HomeController@index')->name('home'); */

Route::get('errorLogin','Auth\LoginController@errorLogin');

/* 
Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback'); */

/* Route::get('google', function () {
    return view('googleAuth');
}); */
   
/* Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback'); */

/* SOCIALITE GOOGLE */

Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');

/* FIN SOCIALITE */

/* RUTAS INCIDENCIAS */

Route::resource('incidencias','IncidenciaController');

Route::resource('incidenciasAdmin','IncidenciaAdminController')->middleware('administrador');

Route::get('/usuarios','UsuariosController@usuarios');
Route::post('/cambioUsuarios','UsuariosController@guardar')/* ->name('something.update') */;

/* Route::get('/incidencias','IncidenciasController@mostrar');

Route::get('/incidenciasCrear','IncidenciasController@crear'); 
Route::post('/guardarIncidencia','IncidenciasController@guardarIncidencia'); */

/* FIN INCIDENCIAS */

/* RUTAS MANUALES EDIT / UPDATE / DELETE  */

Route::get('/incidenciasAdmin/{id}/editar','AdminManualController@editar');
Route::post('/incidenciasAdmin/{id}/actualizar','AdminManualController@actualizar');
Route::get('/incidenciasAdmin/{id}/eliminar', 'AdminManualController@eliminar');

/* Fin rutas MANUALES */

Route::get('/almacenamiento/{archivo}','UsuariosController@verArchivo');

resources/views/incidenciasAdmin/create.blade.php
@extends('layouts.appAdmin')

@section('incidencias')
<div class="container">
    <div class="row">

        <div class="col-lg-12 margin-tb">
    
            <div class="pull-left">
    
                <h2>Crear nueva Incidencia</h2>
            </div>         
        </div>
    </div>
    
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Has metido algún dato erroneo.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
    
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('incidenciasAdmin.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Aula:</strong>
                    <input type="text" name="aula" class="form-control" value="{{old('aula')}}" placeholder="Introduce el aula en la que se encuentra el problema:">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <label for="inputState"><strong>Codigo:</strong></label>
                <select id="inputState" class="form-control" name="codigo">
                    <option value="" disabled selected hidden>Eligue...</option>
                  {{-- <option selected>Choose...</option> --}}
                  <option value="No se enciende la CPU">1- No se enciende la CPU</option>
                  <option value="No se enciende la pantalla">2- No se enciende la pantalla</option>
                  <option value="No entra en mi sesión">3- No entra en mi sesión</option>
                  <option value="No navega en internet">4- No navega en internet</option>
                  <option value="No se oye el sonido">5- No se oye el sonido</option>
                  <option value="No lee CD/DVD">6- No lee CD/DVD</option>
                  <option value="Teclado roto">7- Teclado roto</option>
                  <option value="No funciona el ratón">8- No funciona el ratón</option>
                  <option value="Funcionamiento muy lento">7- Funcionamiento muy lento</option>
                  <option value="Otros">8- Otros, especifíca</option>
                </select>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <label for="inputState"><strong>Estado:</strong></label>
                <select id="inputState" class="form-control" name="estado">
                <option value="0">Enviada</option>
                <option value="1">En proceso</option>
                <option value="2">Finalizada</option>
                </select>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Equipo:</strong>
                    <input type="text" name="equipo" class="form-control" value="{{old('equipo')}}" placeholder="Equipo: Ej. HZ321546">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Descripción: </strong> (máximo 300 carácteres)
                    <textarea class="form-control" style="height:150px" name="descripcion" maxlength="300" onkeyup="countChars(this);" placeholder="Describe el problema...">{{old('descripcion')}}</textarea>
                    <p id="caracteresRestantes" name="caracteresRestantes"></p>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Subir Archivo:</strong>
                    <input type="file" name="archivo[]" class="form-control-file" aria-describedby="descrAyuda" multiple>
                    <small id="descrAyuda" class="form-text text-muted">Archivos soportados: <i>.pdf .doc .csv .jpeg .png .txt .ods (2MB máx. por archivo)</i> </small>
                </div>
            </div>
            
        {{-- <input type="text" name="profesor_id" class="form-control" value="{{Auth::user()->id}}" hidden> --}}
        
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-primary" href="{{ route('incidenciasAdmin.index') }}"> Atrás</a>
                    <button type="submit" class="btn btn-primary">Crear</button>
            </div>
        
        
    </form>
</div>
@endsection

resources/views/incidenciasAdmin/edit.blade.php
@extends('layouts.appAdmin')

@section('incidencias')
<div class="container">
    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Editar incidencia</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('incidenciasAdmin.index') }}"> Volver</a>

            </div>

        </div>

    </div>

   

    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> Has introducido mal algún dato.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif

   

    <form action="{{ route('incidenciasAdmin.update', $incidencia->id ) }}" method="POST"> {{-- method="POST" --}} {{-- action="{{ url('incidenciasAdmin/'. $incidencia->id) }}" method="POST"> --}}

        @csrf

        @method('PUT')

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Aula:</strong>

                    <input type="text" name="aula" value="{{ $incidencia->aula }}" class="form-control" placeholder="Introduce el aula:">

                </div>
                <input type="text" name="id" class="form-control" value="{{$incidencia->id }}" hidden>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <label for="inputState"><strong>Codigo:</strong></label>
                <select id="inputState" class="form-control" name="codigo">
                <option value="{{$incidencia->codigo}}"  selected hidden>{{$incidencia->codigo}}</option>
                  {{-- <option selected>Choose...</option> --}}
                  <option value="No se enciende la CPU">1- No se enciende la CPU</option>
                  <option value="No se enciende la pantalla">2- No se enciende la pantalla</option>
                  <option value="No entra en mi sesión">3- No entra en mi sesión</option>
                  <option value="No navega en internet">4- No navega en internet</option>
                  <option value="No se oye el sonido">5- No se oye el sonido</option>
                  <option value="No lee CD/DVD">6- No lee CD/DVD</option>
                  <option value="Teclado roto">7- Teclado roto</option>
                  <option value="No funciona el ratón">8- No funciona el ratón</option>
                  <option value="Funcionamiento muy lento">7- Funcionamiento muy lento</option>
                  <option value="">8- Otros, especifíca</option>
                </select>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <label for="inputState"><strong>Codigo:</strong></label>
                <select id="inputState" class="form-control" name="estado">
                <option value="{{$incidencia->estado}}"  selected hidden>@switch($incidencia->estado)
                    @case(1)
                        En proceso
                        @break
                    @case(2)
                        Solucionada
                        @break
                    @default
                        Enviada
                @endswitch</option>
                 
                  <option value="0">Enviada</option>
                  <option value="1">En proceso</option>
                  <option value="2">Finalizada</option>
                </select>
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Equipo:</strong>

                    <input type="text" name="equipo" value="{{ $incidencia->equipo }}" class="form-control" placeholder="Introduce el equipo:">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Descripcion:</strong>

                    <textarea class="form-control" style="height:150px" name="descripcion" maxlength="300" onkeyup="countChars(this);" placeholder="Describe el problema...">{{ $incidencia->descripcion }}</textarea>
                    <p id="caracteresRestantes" name="caracteresRestantes"></p>
                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <input type="text" name="profesor_id" class="form-control" value="{{Auth::user()->id}}">
              <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>

   

    </form>
</div>
@endsection

resources/views/incidenciasAdmin/index.blade.php
@extends('layouts.appAdmin')

@section('content')
<div class="container">

    <div id="btnCrearIncidencia">

      <div class="pull-left">

        <a class="btn btn-success" href="{{ route('incidenciasAdmin.create') }}"> Crear Incidencia</a>

    </div>
    
    {{-- Mensajes de ERROR --}}
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Algo ha ido mal.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
    
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {{-- Fin mensajes de ERROR --}}

    {{-- Mensajes de EXITO --}}
    @if ($message = Session::get('success'))

    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>

        <p>{{ $message }}</p>

    </div>
    {{-- <img src="uploads/{{ Session::get('file') }}"> --}}
    @endif
    {{-- Fin mensajes de EXITO --}}

      {{-- Inicio Button/MODAL --}}

      {{-- 
      <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#modalRegisterForm">
            Crear Incidencia
          </button>
          
          <div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Incidencia</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mx-3">
            Por favor, rellene los siguientes campos:
            <br>
            <br>
            <div class="md-form mb-4">
              <i class="fas fa-user prefix grey-text"></i>
              <input type="text" id="aula" class="form-control validate" placeholder="Introduzca Nº Aula de la incidencia:">
             
            </div>
            <div class="md-form mb-4">
              <i class="fas fa-envelope prefix grey-text"></i>
              <input type="text" id="codigo" class="form-control validate" placeholder="Introduzca codigo:">
             
            </div>
    
            <div class="md-form mb-4">
              <i class="fas fa-lock prefix grey-text"></i>
              <input type="text" id="equipo" class="form-control validate" placeholder="Equipo:">
             
            </div>
    
            <div class="md-form mb-4">
                <i class="fas fa-lock prefix grey-text"></i>
                <textarea type="text" id="descripcion" class="form-control validate" placeholder="Explicanos el problema:"></textarea>
               
              </div>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button class="btn btn-secondary btn-lg btn-block">Enviar incidencia</button>
          </div>
        </div>
      </div>
    </div> --}}
    
        {{-- Fin MODAL --}}

    </div>
    {{-- Fin espacio para btn crear --}}

    <div class="row justify-content-center">
        <div class="col-md-14">
            <div class="card">
                <div class="card-header">Tabla de Incidencias</div>

                <div class="card-body">
                   {{--  @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif --}}
                      Bienvenido {{ Auth::user()->name }}, aquí tienes las últimas incidencias
                      <div id="tabla">
                        <table class="table table-striped table-dark table-bordered table-hover">
                                <thead>
                            <tr>
                                <th scope="col" class="align-middle">ID</th>
                                <th scope="col" class="align-middle">AULA</th>
                                <th scope="col" class="align-middle">EQUIPO</th>
                                <th scope="col" class="align-middle">CÓDIGO</th>
                                <th scope="col" class="align-middle">DESCRIPCIÓN</th>
                                <th scope="col" class="align-middle">AUTOR INCIDENCIA</th>
                                <th scope="col" class="align-middle">ADMIN A CARGO</th>
                                <th scope="col" class="align-middle">FECHA</th>
                                <th scope="col" class="align-middle">ÚLTIMA MODIFICACIÓN</th>
                                <th scope="col" class="align-middle">ESTADO</th>
                                <th scope="col" class="align-middle">COMENTARIO</th>
                                <th scope="col" class="align-middle">ARCHIVOS ADJUNTOS</th>
                                <th scope="col" class="align-middle" colspan="2">OPCIONES</th>
                                {{-- <th>ESTADO</th> --}}
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($incidencias as $incidencia)
                              <tr>
                                <td class="align-middle">{{$incidencia->id}}</td>
                                <td class="align-middle">{{$incidencia->aula}}</td>
                                <td class="align-middle">{{$incidencia->equipo}}</td>
                                <td class="align-middle">{{$incidencia->codigo}}</td>
                                <td class="align-middle">{{$incidencia->descripcion}}</td>
                                <td class="align-middle">{{$incidencia->profesor->name}}</td>
                                <td class="align-middle">{{$incidencia->admin['name']}}</td>
                                <td class="align-middle">{{$incidencia->created_at}}</td>
                                <td class="align-middle">{{$incidencia->updated_at}}</td>
                                <td class="align-middle">
                                @switch($incidencia->estado)
                                    @case(1)
                                        <div class="enProceso">En proceso</div>
                                        @break
                                    @case(2)
                                        <div class="solucionada">Solucionada</div>
                                        @break
                                    @default
                                        <div class="enviada">Enviada</div>
                                @endswitch
                              </td>
                            <td class="align-middle">{{$incidencia->comentario}}</td>
                            <td class="align-middle">
                              @foreach (explode(',',$incidencia->archivo) as $item)
                                <a href="/almacenamiento/{{$item}}">{{$item}}</a>
                              @endforeach
                            </td>
                                <td class="align-middle">
                                  {{-- <form action="{{ route('incidenciasAdmin.destroy',$incidencia->id) }}" method="POST"> --}}
                                    {{-- <a class="btn btn-info" href="{{ route('incidencias.show',$incidencia->id) }}">Mostrar</a> --}}
                                    <div class="btnOpciones">
                                      {{-- PRUEBAS --}}
                                    {{-- <a class="btn btn-outline-warning" href="{{ route('incidenciasAdmin.edit',$incidencia->id) }}">Editar</a> --}}
                                     <a class="btn btn-outline-warning" id="editar" href="/incidenciasAdmin/{{$incidencia->id}}/editar">Editar</a> 
                                    @csrf
                                    {{-- @method('DELETE') --}}
                                    {{-- <button type="submit" class="btn btn-outline-danger">Eliminar</button> --}}
                                    <a class="btn btn-outline-danger" id="eliminar" href="/incidenciasAdmin/{{$incidencia->id}}/eliminar">Eliminar</a> 
                                  </div>
                                {{-- </form> --}}
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                        </table>
                
                    </div>
                </div>
            </div>
        </div>
    </div>
  {{--  @foreach ($collection as $item)
       
   @endforeach --}}
</div>

<div class="row d-flex justify-content-center">
  <div style="margin-top:1%;">{!! $incidencias->links() !!}</div>
</div>
@endsection

resources/views/incidenciasAdmin/show.blade.php
@extends('layouts.appProfesores')

@section('incidencias')
<div class="container">
   
</div>
@endsection