routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\UsuariosController;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
/* Route::get('/home', 'HomeController@index')->name('home'); */

Route::get('errorLogin','Auth\LoginController@errorLogin');

/* 
Route::get('/redirect', 'Auth\LoginController@redirectToProvider');
Route::get('/callback', 'Auth\LoginController@handleProviderCallback'); */

/* Route::get('google', function () {
    return view('googleAuth');
}); */
   
/* Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback'); */

/* SOCIALITE GOOGLE */

Route::get('auth/google', 'Auth\LoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\LoginController@handleGoogleCallback');

/* FIN SOCIALITE */

/* RUTAS INCIDENCIAS */

Route::resource('incidencias','IncidenciaController');

Route::resource('incidenciasAdmin','IncidenciaAdminController')->middleware('administrador');

Route::get('/usuarios','UsuariosController@usuarios');
Route::post('/cambioUsuarios','UsuariosController@guardar')/* ->name('something.update') */;

/* Route::get('/incidencias','IncidenciasController@mostrar');

Route::get('/incidenciasCrear','IncidenciasController@crear'); 
Route::post('/guardarIncidencia','IncidenciasController@guardarIncidencia'); */

/* FIN INCIDENCIAS */

/* RUTAS MANUALES EDIT / UPDATE / DELETE  */

Route::get('/incidenciasAdmin/{id}/editar','AdminManualController@editar');
Route::post('/incidenciasAdmin/{id}/actualizar','AdminManualController@actualizar');
Route::get('/incidenciasAdmin/{id}/eliminar', 'AdminManualController@eliminar');

/* Fin rutas MANUALES */

Route::get('/almacenamiento/{archivo}','UsuariosController@verArchivo');

app/Incidencia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Incidencia extends Model
{
    protected $table = 'incidencias';
    
    protected $fillable = [
        'aula', 'codigo', 'equipo', 'descripcion', 'profesor_id', 'estado', 'admin_id', 'comentario', 'archivo',
    ];
    
    /* public function admin(){
        return $this-> belongsTo(Admin::class);
    } */
    public function profesor(){
        return $this-> belongsTo(Profesor::class);
    }
    public function admin(){
      return $this->belongsTo(Profesor::Class,'admin_id');
    }
}

app/Http/Controllers/IncidenciaController.php
<?php

namespace App\Http\Controllers;

use App\Incidencia;
use App\Profesor;
use Illuminate\Http\Request;
use Symfony\Component\Console\Output\ConsoleOutput;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use App\Mail\EnvioMail;
use League\Flysystem\File;
use Illuminate\Support\Facades\Storage;

use Symfony\Component\Console\Input\Input;




class IncidenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /*  $incidencias = DB::table('incidencias')->where('id',Auth::user()->id)->paginate(5); */
        /* $incidencias = Incidencia::latest()->paginate(5); */
        $incidencias = Incidencia::where('profesor_id', Auth::user()->id)->latest()->paginate(5);
        return view('incidencias.index', compact('incidencias'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('incidencias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'aula' => 'required | integer | lte:999',
            'codigo' => 'required | in:No se enciende la CPU,No se enciende la pantalla,No entra en mi sesión,No navega en internet,No se oye el sonido,No lee CD/DVD,Teclado roto,No funciona el ratón,Funcionamiento muy lento,Otros',
            'equipo' => ['required', 'regex:/(HZ[0-9]{6})/u', 'max:8', 'min:8'],
            'descripcion' => 'required | string',
            'archivo.*' => 'mimes:doc,docx,pdf,txt,jpeg,png,ods,xls,xlsx,zip,rar | max:2048',
        ]);

        $adminsMail = DB::table('profesores')->select('email')->where('administrador', true)->get();

        $data = array(
            'aula' => $request->aula,
            'codigo' => $request->codigo,
            'equipo' => $request->equipo,
            'descripcion' => $request->descripcion,
            'email' => Auth::user()->email,
            'nombre' => Auth::user()->name,
            'admins' => $adminsMail,
        );


        /* error_log($adminsMail); */
        /* foreach ($adminsMail as $admin){ */
        Mail::to($adminsMail)->send(new EnvioMail($data));
        /* }; */

        /* $fileName = time().'.'.$request->file->getClientOriginalExtension();  
         $request->file->move(public_path('uploads'), $fileName); */

        /* Otra opcion de ponerle nombre */
        /* $file_route = date('YmdHis') . "." . $file->getClientOriginalExtension(); */
        /* $file = $request->file('archivo');
       
            $destinationPath = 'public/archivos/'; // upload path
            
            $file_route = time() . "_" . $file->getClientOriginalName();
            $file->move($destinationPath, $file_route);
            $insert['archivo'] = "$file_route";  */

        /*  $archivo = $request->file('archivo');
        if ($archivo) {
            $ruta_archivo = time() . "_" . $archivo->getClientOriginalName();
            Storage::disk('archivos_subidos')->put($ruta_archivo, file_get_contents($archivo->getRealPath())); */


        $archivo = $request->file('archivo');
        $arrArchivos = array();
        if ($archivo) {
            foreach ($archivo as $file) {
                $ruta_archivo = time() . "_" . $file->getClientOriginalName();
                array_push($arrArchivos, $ruta_archivo);
                Storage::disk('archivos_subidos')->put($ruta_archivo, file_get_contents($file->getRealPath()));
                error_log($file->getClientOriginalName());
                error_log($ruta_archivo);
            }
        }
        /* error_log($archivo->getClientOriginalName());
            error_log($ruta_archivo); */
        /* error_log($destinationPath); */
        /* } */
        $ruta = implode(',', $arrArchivos);

        $incidencia = new Incidencia();

        $incidencia->aula = $request->aula;
        $incidencia->codigo = $request->codigo;
        $incidencia->equipo = $request->equipo;
        $incidencia->descripcion = $request->descripcion;
        $incidencia->profesor_id = Auth::user()->id;
        /* $incidencia->archivo = $ruta_archivo; */
        $incidencia->archivo = $ruta;

        $incidencia->save();


        /* Incidencia::create($request->all());  // O mediante el metodo save() */


        return redirect()->route('incidencias.index')
            ->with('success', 'Incidencia creada correctamente, se le envio un mail notificando al admin.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Incidencia  $incidencia
     * @return \Illuminate\Http\Response
     */
    public function show(Incidencia $incidencia)
    {
        return view('incidencias.show', compact('incidencia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Incidencia  $incidencia
     * @return \Illuminate\Http\Response
     */
    public function edit(Incidencia $incidencia)
    {

        $user = Auth::user();
        if ($user->can('edit', $incidencia)) {
            return view('incidencias.edit', compact('incidencia'));
        } else {
            return redirect()->route('incidencias.index')
                ->withErrors(['ERROR. No eres propietario de la incidencia que deseas editar']);
        }

        /*  */
        /* if ((Auth::user()->id == $incidencia->profesor_id) || (Auth::user()->administrador=="1")) {
            return view('incidencias.edit', compact('incidencia'));
        } else {
            return redirect()->route('incidencias.index')
            ->withErrors(['ERROR. No eres propietario de la incidencia que deseas editar']);
        } */

        /*  return view('incidencias.edit', compact('incidencia')); */
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Incidencia  $incidencia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Incidencia $incidencia)
    {
        $user = Auth::user();
        if ($user->can('update', $incidencia)) {
            $request->validate([
                'aula' => 'required | integer | lte:999',
                'codigo' => 'required | in:No se enciende la CPU,No se enciende la pantalla,No entra en mi sesión,No navega en internet,No se oye el sonido,No lee CD/DVD,Teclado roto,No funciona el ratón,Funcionamiento muy lento,Otros',
                'equipo' => ['required', 'regex:/(HZ[0-9]{6})/u', 'max:8', 'min:8'],
                'descripcion' => 'required | string',
                'archivo.*' => 'mimes:doc,docx,pdf,txt,jpeg,png,ods,xls,xlsx,zip,rar | max:2048',
            ]);

            /* $incidencia->aula = $request->aula;
            $incidencia->codigo = $request->codigo;
            $incidencia->equipo = $request->equipo;
            $incidencia->descripcion = $request->descripcion;
            //$incidencia->profesor_id = Auth::user()->id;

            $incidencia->save(); */
            $incidencia->update($request->all());
            return redirect()->route('incidencias.index')
                ->with('success', 'Incidencia actualizada satisfactoriamente!');
        } else {
            return redirect()->route('incidencias.index')
                ->withErrors(['ERROR. No eres propietario de la incidencia que deseas actualizar']);
        }

        /* if ((Auth::user()->id == $incidencia->profesor_id) || (Auth::user()->administrador=="1")) {
            $request->validate([
                'aula' => 'required | integer | lte:999',
                'codigo' => 'required | in:No se enciende la CPU,No se enciende la pantalla,No entra en mi sesión,No navega en internet,No se oye el sonido,No lee CD/DVD,Teclado roto,No funciona el ratón,Funcionamiento muy lento,Otros',
                'equipo' => ['required', 'regex:/(HZ[0-9]{6})/u', 'max:8', 'min:8'],
                'descripcion' => 'required | string',
                'archivo.*' => 'mimes:doc,docx,pdf,txt,jpeg,png,ods,xls,xlsx,zip,rar | max:2048',
            ]);
            $incidencia->update($request->all());
            return redirect()->route('incidencias.index')
                ->with('success', 'Incidencia actualizada satisfactoriamente!');
        } else {
            return redirect()->route('incidencias.index')
            ->withErrors(['ERROR. No eres propietario de la incidencia que deseas actualizar']);
        } */
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Incidencia  $incidencia
     * @return \Illuminate\Http\Response
     */
    public function destroy(Incidencia $incidencia)
    {

        $user = Auth::user();
        if ($user->can('delete', $incidencia)) {
            $incidencia->delete();
            return redirect()->route('incidencias.index')
                ->with('success', 'Incidencia eliminada satisfactoriamente!');
        } else {
            return redirect()->route('incidencias.index')
                // ->withErrors(['Error al eliminar', 'No eres propietario de la incidencia']); 
                ->withErrors(['No eres propietario de la incidencia que deseas eliminar']);
        }

        /*  if ((Auth::user()->id == $incidencia->profesor_id) || (Auth::user()->administrador=="1")) {
            $incidencia->delete();
            return redirect()->route('incidencias.index')
                ->with('success', 'Incidencia eliminada satisfactoriamente!');
        } else {
            return redirect()->route('incidencias.index')
            // ->withErrors(['Error al eliminar', 'No eres propietario de la incidencia']); 

app/Http/Controllers/IncidenciasController.php
<?php

namespace App\Http\Controllers;

use App\Incidencia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class IncidenciasController extends Controller
{
   /*  public function index(){
 
        $devices = Device::all();
 
        return view('devices.index',compact('devices'));
    } */

   /*  public function index(){
        $incidencias = Incidencia::latest()->paginate(5);
        return view('incidencias.index',compact('incidencias'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    } */
 
    public function mostrar(){
/* 
        $incidencias = DB::table('incidencias')->get();
        return view('incidencias',['data'=> $incidencias]); */

        $incidencias = Incidencia::latest()->paginate(5);
        return view('incidencias',compact('incidencias'))
            ->with('i', (request()->input('page', 1) - 1) * 5);       
    }


    public function crear(){
        return view('incidenciasCrear');
    }
 
    public function guardarIncidencia(){
 
        $incidencia = new Incidencia();
 
        $incidencia->aula = request('aula');
        $incidencia->codigo = request('codigo');
        $incidencia->equipo = request('equipo');
        $incidencia->descripcion = request('descripcion');
        $incidencia->save();
 
        return redirect('/incidencias');
 
    }

    public function show(Incidencia $incidencia){
        return view('incidenciasShow',compact('incidencia'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */


    public function editar(Incidencia $incidencia){
        return view('incidenciasEditar',compact('incidencia'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, Incidencia $incidencia){
        $request->validate([
            'aula' => 'required',
            'codigo' => 'required',
            'equipo' => 'required',
            'descripcion'=>'required',

        ]);
        $incidencia->update($request->all());
        return redirect()->route('incidencias')
                        ->with('success','Incidencia actualizada satisfactoriamente!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */


    public function eliminar (Incidencia $incidencia){
        $incidencia->delete();
        return redirect()->route('incidencias')
                        ->with('success','Incidencia eliminada satisfactoriamente!');
    }
}

resources/views/incidencias/create.blade.php
@extends('layouts.appProfesores')

@section('incidencias')
<div class="container">
    <div class="row">

        <div class="col-lg-12 margin-tb">
    
            <div class="pull-left">
    
                <h2>Crear nueva Incidencia</h2>
    
            </div>
    
        </div>
    
    </div>
    
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Has metido algún dato erroneo.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
    
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('incidencias.store') }}"  method="POST" enctype="multipart/form-data">
        @csrf
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Aula:</strong>
                    <input type="text" name="aula" class="form-control" value="{{old('aula')}}" placeholder="Introduce el aula en la que se encuentra el problema:">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <label for="inputState"><strong>Codigo:</strong></label>
                <select id="inputState" class="form-control" name="codigo">
                    <option value="" disabled selected hidden>Eligue...</option>
                  {{-- <option selected>Choose...</option> --}}
                  <option value="No se enciende la CPU">1- No se enciende la CPU</option>
                  <option value="No se enciende la pantalla">2- No se enciende la pantalla</option>
                  <option value="No entra en mi sesión">3- No entra en mi sesión</option>
                  <option value="No navega en internet">4- No navega en internet</option>
                  <option value="No se oye el sonido">5- No se oye el sonido</option>
                  <option value="No lee CD/DVD">6- No lee CD/DVD</option>
                  <option value="Teclado roto">7- Teclado roto</option>
                  <option value="No funciona el ratón">8- No funciona el ratón</option>
                  <option value="Funcionamiento muy lento">7- Funcionamiento muy lento</option>
                  <option value="Otros">8- Otros, especifíca en la descripción</option>
                </select>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Equipo:</strong>
                    <input type="text" name="equipo" value="{{old('equipo')}}" class="form-control" placeholder="Equipo: Ej. HZ321546">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Descripción: </strong> (máximo 300 carácteres)
                    <textarea class="form-control" style="height:150px" name="descripcion" maxlength="300" onkeyup="countChars(this);" placeholder="Describe el problema...">{{old('descripcion')}}</textarea>
                    <p id="caracteresRestantes" name="caracteresRestantes"></p>
                </div>
            </div>
            
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Subir Archivo:</strong>
                        <input type="file" name="archivo[]" class="form-control-file" aria-describedby="descrAyuda" multiple>
                        <small id="descrAyuda" class="form-text text-muted">Archivos soportados: <i>.pdf .doc .csv .jpeg .png .txt .ods (2MB máx. por archivo)</i> </small>
                    </div>
                </div>
                

        {{-- <input type="text" name="profesor_id" class="form-control" value="{{Auth::user()->id}}" hidden> --}}
        
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-primary" href="{{ route('incidencias.index') }}"> Atrás</a>
                <button type="submit" class="btn btn-primary">Crear</button>
            </div>
        
        
    </form>
</div>

@endsection

resources/views/incidencias/edit.blade.php
@extends('layouts.appProfesores')

@section('incidencias')
<div class="container">
    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Editar incidencia</h2>

            </div>

            

        </div>

    </div>

   

    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> Has introducido mal algún dato.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif

  

    <form action="{{ route('incidencias.update',$incidencia->id) }}" method="POST">

        @csrf

        @method('PUT')

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Aula:</strong>

                    <input type="text" name="aula" value="{{ $incidencia->aula }}" class="form-control" placeholder="Introduce el aula:">

                </div>

            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <label for="inputState"><strong>Codigo:</strong></label>
                <select id="inputState" class="form-control" name="codigo">
                    <option value="{{$incidencia->codigo}}"  selected hidden>{{$incidencia->codigo}}</option>
                  {{-- <option selected>Choose...</option> --}}
                  <option value="No se enciende la CPU">1- No se enciende la CPU</option>
                  <option value="No se enciende la pantalla">2- No se enciende la pantalla</option>
                  <option value="No entra en mi sesión">3- No entra en mi sesión</option>
                  <option value="No navega en internet">4- No navega en internet</option>
                  <option value="No se oye el sonido">5- No se oye el sonido</option>
                  <option value="No lee CD/DVD">6- No lee CD/DVD</option>
                  <option value="Teclado roto">7- Teclado roto</option>
                  <option value="No funciona el ratón">8- No funciona el ratón</option>
                  <option value="Funcionamiento muy lento">7- Funcionamiento muy lento</option>
                  <option value="">8- Otros, especifíca</option>
                </select>
              </div>
            </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12" style="max-width:100%;padding-left: 0px;padding-right: 0px;">

                <div class="form-group">

                    <strong>Equipo:</strong>

                    <input type="text" name="equipo" value="{{ $incidencia->equipo }}" class="form-control" placeholder="Introduce el equipo:">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Descripcion:</strong>

                    <textarea class="form-control" style="height:150px" name="descripcion" maxlength="300" onkeyup="countChars(this);" placeholder="Describe el problema...">{{ $incidencia->descripcion }}</textarea>
                    <p id="caracteresRestantes" name="caracteresRestantes"></p>
                </div>

            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <a class="btn btn-primary" href="{{ route('incidencias.index') }}"> Volver</a>
                <button type="submit" class="btn btn-primary">Guardar</button>      
            </div>

        </div>

   

    </form>
</div>
@endsection

resources/views/incidencias/show.blade.php
@extends('layouts.appProfesores')

@section('incidencias')
<div class="container">
   
</div>
@endsection